In [161]:
import pandas as pd
import numpy as np

In [162]:
a = pd.DataFrame(np.random.rand(150000,2), columns=["x","y"])

In [163]:
a["date_time"]=np.arange(150000)

In [164]:
a["revisados"]=False

In [165]:
d= pd.date_range("2018-4-01", freq="10s", periods=1000000)

In [169]:
e=np.cumsum(np.random.randint(1,10, 200000))

In [170]:
e

array([     1,      3,     11, ..., 999236, 999239, 999240])

In [171]:
dt=d[e][:150000]

In [172]:
a["date_time"]=dt

In [173]:
a["date_time_1h"]=a["date_time"]+pd.DateOffset(hours=1)

In [174]:
iprincipal = a[a["revisados"]==False].index.min()
iprincipal

0

In [212]:
a.loc[iprincipal, "revisados"]=True

In [213]:
a[(a["revisados"]==False) & (a["date_time"]<=a.loc[iprincipal,"date_time_1h"]) & (a["date_time"] >= a.loc[iprincipal,"date_time"])]

           x         y           date_time  revisados        date_time_1h
1   0.374924  0.212194 2018-04-01 00:00:30      False 2018-04-01 01:00:30
2   0.564192  0.481930 2018-04-01 00:01:50      False 2018-04-01 01:01:50
3   0.604909  0.232955 2018-04-01 00:03:20      False 2018-04-01 01:03:20
4   0.763721  0.778782 2018-04-01 00:03:30      False 2018-04-01 01:03:30
5   0.427516  0.655380 2018-04-01 00:04:40      False 2018-04-01 01:04:40
6   0.437086  0.768542 2018-04-01 00:05:20      False 2018-04-01 01:05:20
7   0.527426  0.869646 2018-04-01 00:06:30      False 2018-04-01 01:06:30
8   0.649027  0.423039 2018-04-01 00:06:40      False 2018-04-01 01:06:40
9   0.153285  0.024504 2018-04-01 00:08:00      False 2018-04-01 01:08:00
10  0.270525  0.093642 2018-04-01 00:09:20      False 2018-04-01 01:09:20
11  0.766634  0.381028 2018-04-01 00:10:30      False 2018-04-01 01:10:30
12  0.836825  0.399964 2018-04-01 00:10:50      False 2018-04-01 01:10:50
13  0.618906  0.948970 2018-04-01 00:11:30      False 2018-04-01 01:11:30
14  0.630174  0.985878 2018-04-01 00:11:50      False 2018-04-01 01:11:50
15  0.305717  0.603661 2018-04-01 00:12:30      False 2018-04-01 01:12:30
16  0.124359  0.271454 2018-04-01 00:13:00      False 2018-04-01 01:13:00
17  0.341526  0.178505 2018-04-01 00:14:10      False 2018-04-01 01:14:10
18  0.901618  0.170534 2018-04-01 00:14:20      False 2018-04-01 01:14:20
19  0.784657  0.725688 2018-04-01 00:15:20      False 2018-04-01 01:15:20
20  0.057575  0.134949 2018-04-01 00:16:10      False 2018-04-01 01:16:10
21  0.460669  0.864429 2018-04-01 00:16:20      False 2018-04-01 01:16:20
22  0.401642  0.007713 2018-04-01 00:17:20      False 2018-04-01 01:17:20
23  0.645582  0.286476 2018-04-01 00:17:30      False 2018-04-01 01:17:30
24  0.162066  0.600214 2018-04-01 00:18:50      False 2018-04-01 01:18:50
25  0.738067  0.642660 2018-04-01 00:20:10      False 2018-04-01 01:20:10
26  0.161572  0.609255 2018-04-01 00:21:00      False 2018-04-01 01:21:00
27  0.379739  0.234364 2018-04-01 00:21:30      False 2018-04-01 01:21:30
28  0.590298  0.760873 2018-04-01 00:21:50      False 2018-04-01 01:21:50
29  0.500452  0.991462 2018-04-01 00:22:10      False 2018-04-01 01:22:10
30  0.994037  0.312564 2018-04-01 00:22:40      False 2018-04-01 01:22:40
..       ...       ...                 ...        ...                 ...
51  0.536208  0.171718 2018-04-01 00:42:20      False 2018-04-01 01:42:20
52  0.295554  0.509066 2018-04-01 00:42:40      False 2018-04-01 01:42:40
53  0.210150  0.716709 2018-04-01 00:44:00      False 2018-04-01 01:44:00
54  0.825793  0.739775 2018-04-01 00:44:40      False 2018-04-01 01:44:40
55  0.515064  0.250160 2018-04-01 00:44:50      False 2018-04-01 01:44:50
56  0.112365  0.635434 2018-04-01 00:45:10      False 2018-04-01 01:45:10
57  0.890154  0.547389 2018-04-01 00:45:20      False 2018-04-01 01:45:20
58  0.125522  0.200318 2018-04-01 00:46:40      False 2018-04-01 01:46:40
59  0.511774  0.819497 2018-04-01 00:47:00      False 2018-04-01 01:47:00
60  0.812820  0.434346 2018-04-01 00:47:20      False 2018-04-01 01:47:20
61  0.972633  0.641764 2018-04-01 00:47:30      False 2018-04-01 01:47:30
62  0.837186  0.732453 2018-04-01 00:48:10      False 2018-04-01 01:48:10
63  0.585337  0.555618 2018-04-01 00:48:40      False 2018-04-01 01:48:40
64  0.520901  0.378692 2018-04-01 00:48:50      False 2018-04-01 01:48:50
65  0.578121  0.079589 2018-04-01 00:50:00      False 2018-04-01 01:50:00
66  0.633690  0.378083 2018-04-01 00:50:10      False 2018-04-01 01:50:10
67  0.077507  0.295211 2018-04-01 00:50:30      False 2018-04-01 01:50:30
68  0.873469  0.622418 2018-04-01 00:51:40      False 2018-04-01 01:51:40
69  0.605865  0.094855 2018-04-01 00:52:40      False 2018-04-01 01:52:40
70  0.017717  0.293268 2018-04-01 00:52:50      False 2018-04-01 01:52:50
71  0.056189  0.878641 2018-04-01 00:54:00      False 2018-04-01 01:54:00
72  0.291279  0.536528 2018-04-01 00:54:30      False 2018-04-01 01:54:30
73  0.212026  0.556505 2018-04-01 00:55:10      False 2018-04-01 01:55:10
74  0.430768  0.044310 2018-04-01 00:56:00      False 2018-04-01 01:56:00
75  0.374364  0.479613 2018-04-01 00:56:50      False 2018-04-01 01:56:50
76  0.256300  0.773798 2018-04-01 00:57:40      False 2018-04-01 01:57:40
77  0.047153  0.772162 2018-04-01 00:58:50      False 2018-04-01 01:58:50
78  0.969945  0.790650 2018-04-01 00:59:00      False 2018-04-01 01:59:00
79  0.726206  0.046887 2018-04-01 00:59:40      False 2018-04-01 01:59:40
80  0.663296  0.505668 2018-04-01 00:59:50      False 2018-04-01 01:59:50

[80 rows x 5 columns]

In [183]:
a

               x         y           date_time  revisados        date_time_1h
0       0.913680  0.030410 2018-04-01 00:00:10       True 2018-04-01 01:00:10
1       0.374924  0.212194 2018-04-01 00:00:30      False 2018-04-01 01:00:30
2       0.564192  0.481930 2018-04-01 00:01:50      False 2018-04-01 01:01:50
3       0.604909  0.232955 2018-04-01 00:03:20      False 2018-04-01 01:03:20
4       0.763721  0.778782 2018-04-01 00:03:30      False 2018-04-01 01:03:30
5       0.427516  0.655380 2018-04-01 00:04:40      False 2018-04-01 01:04:40
6       0.437086  0.768542 2018-04-01 00:05:20      False 2018-04-01 01:05:20
7       0.527426  0.869646 2018-04-01 00:06:30      False 2018-04-01 01:06:30
8       0.649027  0.423039 2018-04-01 00:06:40      False 2018-04-01 01:06:40
9       0.153285  0.024504 2018-04-01 00:08:00      False 2018-04-01 01:08:00
10      0.270525  0.093642 2018-04-01 00:09:20      False 2018-04-01 01:09:20
11      0.766634  0.381028 2018-04-01 00:10:30      False 2018-04-01 01:10:30
12      0.836825  0.399964 2018-04-01 00:10:50      False 2018-04-01 01:10:50
13      0.618906  0.948970 2018-04-01 00:11:30      False 2018-04-01 01:11:30
14      0.630174  0.985878 2018-04-01 00:11:50      False 2018-04-01 01:11:50
15      0.305717  0.603661 2018-04-01 00:12:30      False 2018-04-01 01:12:30
16      0.124359  0.271454 2018-04-01 00:13:00      False 2018-04-01 01:13:00
17      0.341526  0.178505 2018-04-01 00:14:10      False 2018-04-01 01:14:10
18      0.901618  0.170534 2018-04-01 00:14:20      False 2018-04-01 01:14:20
19      0.784657  0.725688 2018-04-01 00:15:20      False 2018-04-01 01:15:20
20      0.057575  0.134949 2018-04-01 00:16:10      False 2018-04-01 01:16:10
21      0.460669  0.864429 2018-04-01 00:16:20      False 2018-04-01 01:16:20
22      0.401642  0.007713 2018-04-01 00:17:20      False 2018-04-01 01:17:20
23      0.645582  0.286476 2018-04-01 00:17:30      False 2018-04-01 01:17:30
24      0.162066  0.600214 2018-04-01 00:18:50      False 2018-04-01 01:18:50
25      0.738067  0.642660 2018-04-01 00:20:10      False 2018-04-01 01:20:10
26      0.161572  0.609255 2018-04-01 00:21:00      False 2018-04-01 01:21:00
27      0.379739  0.234364 2018-04-01 00:21:30      False 2018-04-01 01:21:30
28      0.590298  0.760873 2018-04-01 00:21:50      False 2018-04-01 01:21:50
29      0.500452  0.991462 2018-04-01 00:22:10      False 2018-04-01 01:22:10
...          ...       ...                 ...        ...                 ...
149970  0.135946  0.216327 2018-06-26 19:44:10      False 2018-06-26 20:44:10
149971  0.848070  0.541736 2018-06-26 19:45:40      False 2018-06-26 20:45:40
149972  0.714049  0.351951 2018-06-26 19:46:50      False 2018-06-26 20:46:50
149973  0.799935  0.465918 2018-06-26 19:47:40      False 2018-06-26 20:47:40
149974  0.449332  0.735370 2018-06-26 19:48:20      False 2018-06-26 20:48:20
149975  0.522118  0.486065 2018-06-26 19:48:30      False 2018-06-26 20:48:30
149976  0.697544  0.741030 2018-06-26 19:48:40      False 2018-06-26 20:48:40
149977  0.839771  0.716904 2018-06-26 19:49:10      False 2018-06-26 20:49:10
149978  0.504816  0.874845 2018-06-26 19:50:20      False 2018-06-26 20:50:20
149979  0.605291  0.549195 2018-06-26 19:50:30      False 2018-06-26 20:50:30
149980  0.149343  0.709730 2018-06-26 19:51:10      False 2018-06-26 20:51:10
149981  0.398033  0.933013 2018-06-26 19:52:40      False 2018-06-26 20:52:40
149982  0.900767  0.750654 2018-06-26 19:53:20      False 2018-06-26 20:53:20
149983  0.441913  0.461554 2018-06-26 19:54:50      False 2018-06-26 20:54:50
149984  0.516154  0.262386 2018-06-26 19:55:00      False 2018-06-26 20:55:00
149985  0.012187  0.998097 2018-06-26 19:55:40      False 2018-06-26 20:55:40
149986  0.039750  0.546891 2018-06-26 19:56:10      False 2018-06-26 20:56:10
149987  0.238793  0.509458 2018-06-26 19:56:50      False 2018-06-26 20:56:50
149988  0.637371  0.348855 2018-06-26 19:58:20      False 2018-06-26 20:58:20
149989  0.979971  0.211596 2018-06-26 19:59:40      False 2018-06-26 20:59:40
149990  0.519877  0.180617 2018-06-26 19:59:50      False 2018-06-26 20:59:50
149991  0.944367  0.032588 2018-06-26 20:01:10      False 2018-06-26 21:01:10
149992  0.664690  0.423775 2018-06-26 20:02:10      False 2018-06-26 21:02:10
149993  0.552126  0.118781 2018-06-26 20:03:30      False 2018-06-26 21:03:30
149994  0.055983  0.517669 2018-06-26 20:04:30      False 2018-06-26 21:04:30
149995  0.586568  0.443927 2018-06-26 20:06:00      False 2018-06-26 21:06:00
149996  0.940259  0.875512 2018-06-26 20:06:30      False 2018-06-26 21:06:30
149997  0.546042  0.124896 2018-06-26 20:06:40      False 2018-06-26 21:06:40
149998  0.333861  0.653334 2018-06-26 20:07:30      False 2018-06-26 21:07:30
149999  0.577953  0.355618 2018-06-26 20:08:30      False 2018-06-26 21:08:30

[150000 rows x 5 columns]

In [ ]:
a["distancia"]

In [184]:
a

               x         y           date_time  revisados        date_time_1h
0       0.913680  0.030410 2018-04-01 00:00:10       True 2018-04-01 01:00:10
1       0.374924  0.212194 2018-04-01 00:00:30      False 2018-04-01 01:00:30
2       0.564192  0.481930 2018-04-01 00:01:50      False 2018-04-01 01:01:50
3       0.604909  0.232955 2018-04-01 00:03:20      False 2018-04-01 01:03:20
4       0.763721  0.778782 2018-04-01 00:03:30      False 2018-04-01 01:03:30
5       0.427516  0.655380 2018-04-01 00:04:40      False 2018-04-01 01:04:40
6       0.437086  0.768542 2018-04-01 00:05:20      False 2018-04-01 01:05:20
7       0.527426  0.869646 2018-04-01 00:06:30      False 2018-04-01 01:06:30
8       0.649027  0.423039 2018-04-01 00:06:40      False 2018-04-01 01:06:40
9       0.153285  0.024504 2018-04-01 00:08:00      False 2018-04-01 01:08:00
10      0.270525  0.093642 2018-04-01 00:09:20      False 2018-04-01 01:09:20
11      0.766634  0.381028 2018-04-01 00:10:30      False 2018-04-01 01:10:30
12      0.836825  0.399964 2018-04-01 00:10:50      False 2018-04-01 01:10:50
13      0.618906  0.948970 2018-04-01 00:11:30      False 2018-04-01 01:11:30
14      0.630174  0.985878 2018-04-01 00:11:50      False 2018-04-01 01:11:50
15      0.305717  0.603661 2018-04-01 00:12:30      False 2018-04-01 01:12:30
16      0.124359  0.271454 2018-04-01 00:13:00      False 2018-04-01 01:13:00
17      0.341526  0.178505 2018-04-01 00:14:10      False 2018-04-01 01:14:10
18      0.901618  0.170534 2018-04-01 00:14:20      False 2018-04-01 01:14:20
19      0.784657  0.725688 2018-04-01 00:15:20      False 2018-04-01 01:15:20
20      0.057575  0.134949 2018-04-01 00:16:10      False 2018-04-01 01:16:10
21      0.460669  0.864429 2018-04-01 00:16:20      False 2018-04-01 01:16:20
22      0.401642  0.007713 2018-04-01 00:17:20      False 2018-04-01 01:17:20
23      0.645582  0.286476 2018-04-01 00:17:30      False 2018-04-01 01:17:30
24      0.162066  0.600214 2018-04-01 00:18:50      False 2018-04-01 01:18:50
25      0.738067  0.642660 2018-04-01 00:20:10      False 2018-04-01 01:20:10
26      0.161572  0.609255 2018-04-01 00:21:00      False 2018-04-01 01:21:00
27      0.379739  0.234364 2018-04-01 00:21:30      False 2018-04-01 01:21:30
28      0.590298  0.760873 2018-04-01 00:21:50      False 2018-04-01 01:21:50
29      0.500452  0.991462 2018-04-01 00:22:10      False 2018-04-01 01:22:10
...          ...       ...                 ...        ...                 ...
149970  0.135946  0.216327 2018-06-26 19:44:10      False 2018-06-26 20:44:10
149971  0.848070  0.541736 2018-06-26 19:45:40      False 2018-06-26 20:45:40
149972  0.714049  0.351951 2018-06-26 19:46:50      False 2018-06-26 20:46:50
149973  0.799935  0.465918 2018-06-26 19:47:40      False 2018-06-26 20:47:40
149974  0.449332  0.735370 2018-06-26 19:48:20      False 2018-06-26 20:48:20
149975  0.522118  0.486065 2018-06-26 19:48:30      False 2018-06-26 20:48:30
149976  0.697544  0.741030 2018-06-26 19:48:40      False 2018-06-26 20:48:40
149977  0.839771  0.716904 2018-06-26 19:49:10      False 2018-06-26 20:49:10
149978  0.504816  0.874845 2018-06-26 19:50:20      False 2018-06-26 20:50:20
149979  0.605291  0.549195 2018-06-26 19:50:30      False 2018-06-26 20:50:30
149980  0.149343  0.709730 2018-06-26 19:51:10      False 2018-06-26 20:51:10
149981  0.398033  0.933013 2018-06-26 19:52:40      False 2018-06-26 20:52:40
149982  0.900767  0.750654 2018-06-26 19:53:20      False 2018-06-26 20:53:20
149983  0.441913  0.461554 2018-06-26 19:54:50      False 2018-06-26 20:54:50
149984  0.516154  0.262386 2018-06-26 19:55:00      False 2018-06-26 20:55:00
149985  0.012187  0.998097 2018-06-26 19:55:40      False 2018-06-26 20:55:40
149986  0.039750  0.546891 2018-06-26 19:56:10      False 2018-06-26 20:56:10
149987  0.238793  0.509458 2018-06-26 19:56:50      False 2018-06-26 20:56:50
149988  0.637371  0.348855 2018-06-26 19:58:20      False 2018-06-26 20:58:20
149989  0.979971  0.211596 2018-06-26 19:59:40      False 2018-06-26 20:59:40
149990  0.519877  0.180617 2018-06-26 19:59:50      False 2018-06-26 20:59:50
149991  0.944367  0.032588 2018-06-26 20:01:10      False 2018-06-26 21:01:10
149992  0.664690  0.423775 2018-06-26 20:02:10      False 2018-06-26 21:02:10
149993  0.552126  0.118781 2018-06-26 20:03:30      False 2018-06-26 21:03:30
149994  0.055983  0.517669 2018-06-26 20:04:30      False 2018-06-26 21:04:30
149995  0.586568  0.443927 2018-06-26 20:06:00      False 2018-06-26 21:06:00
149996  0.940259  0.875512 2018-06-26 20:06:30      False 2018-06-26 21:06:30
149997  0.546042  0.124896 2018-06-26 20:06:40      False 2018-06-26 21:06:40
149998  0.333861  0.653334 2018-06-26 20:07:30      False 2018-06-26 21:07:30
149999  0.577953  0.355618 2018-06-26 20:08:30      False 2018-06-26 21:08:30

[150000 rows x 5 columns]

In [214]:
e=a[(a["revisados"]==False) & (a["date_time"]<=a.loc[iprincipal,"date_time_1h"]) & (a["date_time"] >= a.loc[iprincipal,"date_time"])]

In [215]:
e

           x         y           date_time  revisados        date_time_1h
1   0.374924  0.212194 2018-04-01 00:00:30      False 2018-04-01 01:00:30
2   0.564192  0.481930 2018-04-01 00:01:50      False 2018-04-01 01:01:50
3   0.604909  0.232955 2018-04-01 00:03:20      False 2018-04-01 01:03:20
4   0.763721  0.778782 2018-04-01 00:03:30      False 2018-04-01 01:03:30
5   0.427516  0.655380 2018-04-01 00:04:40      False 2018-04-01 01:04:40
6   0.437086  0.768542 2018-04-01 00:05:20      False 2018-04-01 01:05:20
7   0.527426  0.869646 2018-04-01 00:06:30      False 2018-04-01 01:06:30
8   0.649027  0.423039 2018-04-01 00:06:40      False 2018-04-01 01:06:40
9   0.153285  0.024504 2018-04-01 00:08:00      False 2018-04-01 01:08:00
10  0.270525  0.093642 2018-04-01 00:09:20      False 2018-04-01 01:09:20
11  0.766634  0.381028 2018-04-01 00:10:30      False 2018-04-01 01:10:30
12  0.836825  0.399964 2018-04-01 00:10:50      False 2018-04-01 01:10:50
13  0.618906  0.948970 2018-04-01 00:11:30      False 2018-04-01 01:11:30
14  0.630174  0.985878 2018-04-01 00:11:50      False 2018-04-01 01:11:50
15  0.305717  0.603661 2018-04-01 00:12:30      False 2018-04-01 01:12:30
16  0.124359  0.271454 2018-04-01 00:13:00      False 2018-04-01 01:13:00
17  0.341526  0.178505 2018-04-01 00:14:10      False 2018-04-01 01:14:10
18  0.901618  0.170534 2018-04-01 00:14:20      False 2018-04-01 01:14:20
19  0.784657  0.725688 2018-04-01 00:15:20      False 2018-04-01 01:15:20
20  0.057575  0.134949 2018-04-01 00:16:10      False 2018-04-01 01:16:10
21  0.460669  0.864429 2018-04-01 00:16:20      False 2018-04-01 01:16:20
22  0.401642  0.007713 2018-04-01 00:17:20      False 2018-04-01 01:17:20
23  0.645582  0.286476 2018-04-01 00:17:30      False 2018-04-01 01:17:30
24  0.162066  0.600214 2018-04-01 00:18:50      False 2018-04-01 01:18:50
25  0.738067  0.642660 2018-04-01 00:20:10      False 2018-04-01 01:20:10
26  0.161572  0.609255 2018-04-01 00:21:00      False 2018-04-01 01:21:00
27  0.379739  0.234364 2018-04-01 00:21:30      False 2018-04-01 01:21:30
28  0.590298  0.760873 2018-04-01 00:21:50      False 2018-04-01 01:21:50
29  0.500452  0.991462 2018-04-01 00:22:10      False 2018-04-01 01:22:10
30  0.994037  0.312564 2018-04-01 00:22:40      False 2018-04-01 01:22:40
..       ...       ...                 ...        ...                 ...
51  0.536208  0.171718 2018-04-01 00:42:20      False 2018-04-01 01:42:20
52  0.295554  0.509066 2018-04-01 00:42:40      False 2018-04-01 01:42:40
53  0.210150  0.716709 2018-04-01 00:44:00      False 2018-04-01 01:44:00
54  0.825793  0.739775 2018-04-01 00:44:40      False 2018-04-01 01:44:40
55  0.515064  0.250160 2018-04-01 00:44:50      False 2018-04-01 01:44:50
56  0.112365  0.635434 2018-04-01 00:45:10      False 2018-04-01 01:45:10
57  0.890154  0.547389 2018-04-01 00:45:20      False 2018-04-01 01:45:20
58  0.125522  0.200318 2018-04-01 00:46:40      False 2018-04-01 01:46:40
59  0.511774  0.819497 2018-04-01 00:47:00      False 2018-04-01 01:47:00
60  0.812820  0.434346 2018-04-01 00:47:20      False 2018-04-01 01:47:20
61  0.972633  0.641764 2018-04-01 00:47:30      False 2018-04-01 01:47:30
62  0.837186  0.732453 2018-04-01 00:48:10      False 2018-04-01 01:48:10
63  0.585337  0.555618 2018-04-01 00:48:40      False 2018-04-01 01:48:40
64  0.520901  0.378692 2018-04-01 00:48:50      False 2018-04-01 01:48:50
65  0.578121  0.079589 2018-04-01 00:50:00      False 2018-04-01 01:50:00
66  0.633690  0.378083 2018-04-01 00:50:10      False 2018-04-01 01:50:10
67  0.077507  0.295211 2018-04-01 00:50:30      False 2018-04-01 01:50:30
68  0.873469  0.622418 2018-04-01 00:51:40      False 2018-04-01 01:51:40
69  0.605865  0.094855 2018-04-01 00:52:40      False 2018-04-01 01:52:40
70  0.017717  0.293268 2018-04-01 00:52:50      False 2018-04-01 01:52:50
71  0.056189  0.878641 2018-04-01 00:54:00      False 2018-04-01 01:54:00
72  0.291279  0.536528 2018-04-01 00:54:30      False 2018-04-01 01:54:30
73  0.212026  0.556505 2018-04-01 00:55:10      False 2018-04-01 01:55:10
74  0.430768  0.044310 2018-04-01 00:56:00      False 2018-04-01 01:56:00
75  0.374364  0.479613 2018-04-01 00:56:50      False 2018-04-01 01:56:50
76  0.256300  0.773798 2018-04-01 00:57:40      False 2018-04-01 01:57:40
77  0.047153  0.772162 2018-04-01 00:58:50      False 2018-04-01 01:58:50
78  0.969945  0.790650 2018-04-01 00:59:00      False 2018-04-01 01:59:00
79  0.726206  0.046887 2018-04-01 00:59:40      False 2018-04-01 01:59:40
80  0.663296  0.505668 2018-04-01 00:59:50      False 2018-04-01 01:59:50

[80 rows x 5 columns]

In [216]:
e.is_copy=False
e["distancia"]=np.random.randint(1,500,80)

In [217]:
e

,x,y,date_time,revisados,date_time_1h,distancia
1,0.374924,0.212194,2018-04-01 00:00:30,False,2018-04-01 01:00:30,78
2,0.564192,0.481930,2018-04-01 00:01:50,False,2018-04-01 01:01:50,5
3,0.604909,0.232955,2018-04-01 00:03:20,False,2018-04-01 01:03:20,406
4,0.763721,0.778782,2018-04-01 00:03:30,False,2018-04-01 01:03:30,329
5,0.427516,0.655380,2018-04-01 00:04:40,False,2018-04-01 01:04:40,393
6,0.437086,0.768542,2018-04-01 00:05:20,False,2018-04-01 01:05:20,481
7,0.527426,0.869646,2018-04-01 00:06:30,False,2018-04-01 01:06:30,178
8,0.649027,0.423039,2018-04-01 00:06:40,False,2018-04-01 01:06:40,66
9,0.153285,0.024504,2018-04-01 00:08:00,False,2018-04-01 01:08:00,485
10,0.270525,0.093642,2018-04-01 00:09:20,False,2018-04-01 01:09:20,196
11,0.766634,0.381028,2018-04-01 00:10:30,False,2018-04-01 01:10:30,38
12,0.836825,0.399964,2018-04-01 00:10:50,False,2018-04-01 01:10:50,473
13,0.618906,0.948970,2018-04-01 00:11:30,False,2018-04-01 01:11:30,294
14,0.630174,0.985878,2018-04-01 00:11:50,False,2018-04-01 01:11:50,476
15,0.305717,0.603661,2018-04-01 00:12:30,False,2018-04-01 01:12:30,369
16,0.124359,0.271454,2018-04-01 00:13:00,False,2018-04-01 01:13:00,191
17,0.341526,0.178505,2018-04-01 00:14:10,False,2018-04-01 01:14:10,325
18,0.901618,0.170534,2018-04-01 00:14:20,False,2018-04-01 01:14:20,96
19,0.784657,0.725688,2018-04-01 00:15:20,False,2018-04-01 01:15:20,368
20,0.057575,0.134949,2018-04-01 00:16:10,False,2018-04-01 01:16:10,426
21,0.460669,0.864429,2018-04-01 00:16:20,False,2018-04-01 01:16:20,303
22,0.401642,0.007713,2018-04-01 00:17:20,False,2018-04-01 01:17:20,486
23,0.645582,0.286476,2018-04-01 00:17:30,False,2018-04-01 01:17:30,97
24,0.162066,0.600214,2018-04-01 00:18:50,False,2018-04-01 01:18:50,181
25,0.738067,0.642660,2018-04-01 00:20:10,False,2018-04-01 01:20:10,474
26,0.161572,0.609255,2018-04-01 00:21:00,False,2018-04-01 01:21:00,199
27,0.379739,0.234364,2018-04-01 00:21:30,False,2018-04-01 01:21:30,10
28,0.590298,0.760873,2018-04-01 00:21:50,False,2018-04-01 01:21:50,310
29,0.500452,0.991462,2018-04-01 00:22:10,False,2018-04-01 01:22:10,136
30,0.994037,0.312564,2018-04-01 00:22:40,False,2018-04-01 01:22:40,238
...,...,...,...,...,...,...
51,0.536208,0.171718,2018-04-01 00:42:20,False,2018-04-01 01:42:20,1
52,0.295554,0.509066,2018-04-01 00:42:40,False,2018-04-01 01:42:40,311
53,0.210150,0.716709,2018-04-01 00:44:00,False,2018-04-01 01:44:00,70
54,0.825793,0.739775,2018-04-01 00:44:40,False,2018-04-01 01:44:40,323
55,0.515064,0.250160,2018-04-01 00:44:50,False,2018-04-01 01:44:50,486
56,0.112365,0.635434,2018-04-01 00:45:10,False,2018-04-01 01:45:10,61
57,0.890154,0.547389,2018-04-01 00:45:20,False,2018-04-01 01:45:20,495
58,0.125522,0.200318,2018-04-01 00:46:40,False,2018-04-01 01:46:40,135
59,0.511774,0.819497,2018-04-01 00:47:00,False,2018-04-01 01:47:00,21
60,0.812820,0.434346,2018-04-01 00:47:20,False,2018-04-01 01:47:20,254
61,0.972633,0.641764,2018-04-01 00:47:30,False,2018-04-01 01:47:30,300
62,0.837186,0.732453,2018-04-01 00:48:10,False,2018-04-01 01:48:10,246
63,0.585337,0.555618,2018-04-01 00:48:40,False,2018-04-01 01:48:40,31
64,0.520901,0.378692,2018-04-01 00:48:50,False,2018-04-01 01:48:50,433
65,0.578121,0.079589,2018-04-01 00:50:00,False,2018-04-01 01:50:00,326
66,0.633690,0.378083,2018-04-01 00:50:10,False,2018-04-01 01:50:10,455
67,0.077507,0.295211,2018-04-01 00:50:30,False,2018-04-01 01:50:30,92
68,0.873469,0.622418,2018-04-01 00:51:40,False,2018-04-01 01:51:40,91
69,0.605865,0.094855,2018-04-01 00:52:40,False,2018-04-01 01:52:40,170
70,0.017717,0.293268,2018-04-01 00:52:50,False,2018-04-01 01:52:50,55
71,0.056189,0.878641,2018-04-01 00:54:00,False,2018-04-01 01:54:00,436
72,0.291279,0.536528,2018-04-01 00:54:30,False,2018-04-01 01:54:30,394
73,0.212026,0.556505,2018-04-01 00:55:10,False,2018-04-01 01:55:10,309
74,0.430768,0.044310,2018-04-01 00:56:00,False,2018-04-01 01:56:00,154
75,0.374364,0.479613,2018-04-01 00:56:50,False,2018-04-01 01:56:50,169
76,0.256300,0.773798,2018-04-01 00:57:40,False,2018-04-01 01:57:40,99
77,0.047153,0.772162,2018-04-01 00:58:50,False,2018-04-01 01:58:50,17
78,0.969945,0.790650,2018-04-01 00:59:00,False,2018-04-01 01:59:00,483
79,0.726206,0.046887,2018-04-01 00:59:40,False,2018-04-01 01:59:40,413
80,0.663296,0.505668,2018-04-01 00:59:50,False,2018-04-01 01:59:50,150

In [218]:
f=e[e["distancia"]<=150]
f.is_copy=False
f["revisados"]=True

In [219]:
f

,x,y,date_time,revisados,date_time_1h,distancia
1,0.374924,0.212194,2018-04-01 00:00:30,True,2018-04-01 01:00:30,78
2,0.564192,0.481930,2018-04-01 00:01:50,True,2018-04-01 01:01:50,5
8,0.649027,0.423039,2018-04-01 00:06:40,True,2018-04-01 01:06:40,66
11,0.766634,0.381028,2018-04-01 00:10:30,True,2018-04-01 01:10:30,38
18,0.901618,0.170534,2018-04-01 00:14:20,True,2018-04-01 01:14:20,96
23,0.645582,0.286476,2018-04-01 00:17:30,True,2018-04-01 01:17:30,97
27,0.379739,0.234364,2018-04-01 00:21:30,True,2018-04-01 01:21:30,10
29,0.500452,0.991462,2018-04-01 00:22:10,True,2018-04-01 01:22:10,136
32,0.769657,0.752405,2018-04-01 00:25:00,True,2018-04-01 01:25:00,96
33,0.825620,0.315826,2018-04-01 00:26:30,True,2018-04-01 01:26:30,56
40,0.243094,0.362951,2018-04-01 00:31:00,True,2018-04-01 01:31:00,115
45,0.844143,0.357275,2018-04-01 00:36:40,True,2018-04-01 01:36:40,125
50,0.162292,0.151362,2018-04-01 00:41:20,True,2018-04-01 01:41:20,22
51,0.536208,0.171718,2018-04-01 00:42:20,True,2018-04-01 01:42:20,1
53,0.210150,0.716709,2018-04-01 00:44:00,True,2018-04-01 01:44:00,70
56,0.112365,0.635434,2018-04-01 00:45:10,True,2018-04-01 01:45:10,61
58,0.125522,0.200318,2018-04-01 00:46:40,True,2018-04-01 01:46:40,135
59,0.511774,0.819497,2018-04-01 00:47:00,True,2018-04-01 01:47:00,21
63,0.585337,0.555618,2018-04-01 00:48:40,True,2018-04-01 01:48:40,31
67,0.077507,0.295211,2018-04-01 00:50:30,True,2018-04-01 01:50:30,92
68,0.873469,0.622418,2018-04-01 00:51:40,True,2018-04-01 01:51:40,91
70,0.017717,0.293268,2018-04-01 00:52:50,True,2018-04-01 01:52:50,55
76,0.256300,0.773798,2018-04-01 00:57:40,True,2018-04-01 01:57:40,99
77,0.047153,0.772162,2018-04-01 00:58:50,True,2018-04-01 01:58:50,17
80,0.663296,0.505668,2018-04-01 00:59:50,True,2018-04-01 01:59:50,150

In [211]:
a

               x         y           date_time  revisados        date_time_1h
0       0.913680  0.030410 2018-04-01 00:00:10       True 2018-04-01 01:00:10
1       0.374924  0.212194 2018-04-01 00:00:30      False 2018-04-01 01:00:30
2       0.564192  0.481930 2018-04-01 00:01:50      False 2018-04-01 01:01:50
3       0.604909  0.232955 2018-04-01 00:03:20      False 2018-04-01 01:03:20
4       0.763721  0.778782 2018-04-01 00:03:30      False 2018-04-01 01:03:30
5       0.427516  0.655380 2018-04-01 00:04:40      False 2018-04-01 01:04:40
6       0.437086  0.768542 2018-04-01 00:05:20      False 2018-04-01 01:05:20
7       0.527426  0.869646 2018-04-01 00:06:30      False 2018-04-01 01:06:30
8       0.649027  0.423039 2018-04-01 00:06:40      False 2018-04-01 01:06:40
9       0.153285  0.024504 2018-04-01 00:08:00      False 2018-04-01 01:08:00
10      0.270525  0.093642 2018-04-01 00:09:20      False 2018-04-01 01:09:20
11      0.766634  0.381028 2018-04-01 00:10:30      False 2018-04-01 01:10:30
12      0.836825  0.399964 2018-04-01 00:10:50      False 2018-04-01 01:10:50
13      0.618906  0.948970 2018-04-01 00:11:30      False 2018-04-01 01:11:30
14      0.630174  0.985878 2018-04-01 00:11:50      False 2018-04-01 01:11:50
15      0.305717  0.603661 2018-04-01 00:12:30      False 2018-04-01 01:12:30
16      0.124359  0.271454 2018-04-01 00:13:00      False 2018-04-01 01:13:00
17      0.341526  0.178505 2018-04-01 00:14:10      False 2018-04-01 01:14:10
18      0.901618  0.170534 2018-04-01 00:14:20      False 2018-04-01 01:14:20
19      0.784657  0.725688 2018-04-01 00:15:20      False 2018-04-01 01:15:20
20      0.057575  0.134949 2018-04-01 00:16:10      False 2018-04-01 01:16:10
21      0.460669  0.864429 2018-04-01 00:16:20      False 2018-04-01 01:16:20
22      0.401642  0.007713 2018-04-01 00:17:20      False 2018-04-01 01:17:20
23      0.645582  0.286476 2018-04-01 00:17:30      False 2018-04-01 01:17:30
24      0.162066  0.600214 2018-04-01 00:18:50      False 2018-04-01 01:18:50
25      0.738067  0.642660 2018-04-01 00:20:10      False 2018-04-01 01:20:10
26      0.161572  0.609255 2018-04-01 00:21:00      False 2018-04-01 01:21:00
27      0.379739  0.234364 2018-04-01 00:21:30      False 2018-04-01 01:21:30
28      0.590298  0.760873 2018-04-01 00:21:50      False 2018-04-01 01:21:50
29      0.500452  0.991462 2018-04-01 00:22:10      False 2018-04-01 01:22:10
...          ...       ...                 ...        ...                 ...
149970  0.135946  0.216327 2018-06-26 19:44:10      False 2018-06-26 20:44:10
149971  0.848070  0.541736 2018-06-26 19:45:40      False 2018-06-26 20:45:40
149972  0.714049  0.351951 2018-06-26 19:46:50      False 2018-06-26 20:46:50
149973  0.799935  0.465918 2018-06-26 19:47:40      False 2018-06-26 20:47:40
149974  0.449332  0.735370 2018-06-26 19:48:20      False 2018-06-26 20:48:20
149975  0.522118  0.486065 2018-06-26 19:48:30      False 2018-06-26 20:48:30
149976  0.697544  0.741030 2018-06-26 19:48:40      False 2018-06-26 20:48:40
149977  0.839771  0.716904 2018-06-26 19:49:10      False 2018-06-26 20:49:10
149978  0.504816  0.874845 2018-06-26 19:50:20      False 2018-06-26 20:50:20
149979  0.605291  0.549195 2018-06-26 19:50:30      False 2018-06-26 20:50:30
149980  0.149343  0.709730 2018-06-26 19:51:10      False 2018-06-26 20:51:10
149981  0.398033  0.933013 2018-06-26 19:52:40      False 2018-06-26 20:52:40
149982  0.900767  0.750654 2018-06-26 19:53:20      False 2018-06-26 20:53:20
149983  0.441913  0.461554 2018-06-26 19:54:50      False 2018-06-26 20:54:50
149984  0.516154  0.262386 2018-06-26 19:55:00      False 2018-06-26 20:55:00
149985  0.012187  0.998097 2018-06-26 19:55:40      False 2018-06-26 20:55:40
149986  0.039750  0.546891 2018-06-26 19:56:10      False 2018-06-26 20:56:10
149987  0.238793  0.509458 2018-06-26 19:56:50      False 2018-06-26 20:56:50
149988  0.637371  0.348855 2018-06-26 19:58:20      False 2018-06-26 20:58:20
149989  0.979971  0.211596 2018-06-26 19:59:40      False 2018-06-26 20:59:40
149990  0.519877  0.180617 2018-06-26 19:59:50      False 2018-06-26 20:59:50
149991  0.944367  0.032588 2018-06-26 20:01:10      False 2018-06-26 21:01:10
149992  0.664690  0.423775 2018-06-26 20:02:10      False 2018-06-26 21:02:10
149993  0.552126  0.118781 2018-06-26 20:03:30      False 2018-06-26 21:03:30
149994  0.055983  0.517669 2018-06-26 20:04:30      False 2018-06-26 21:04:30
149995  0.586568  0.443927 2018-06-26 20:06:00      False 2018-06-26 21:06:00
149996  0.940259  0.875512 2018-06-26 20:06:30      False 2018-06-26 21:06:30
149997  0.546042  0.124896 2018-06-26 20:06:40      False 2018-06-26 21:06:40
149998  0.333861  0.653334 2018-06-26 20:07:30      False 2018-06-26 21:07:30
149999  0.577953  0.355618 2018-06-26 20:08:30      False 2018-06-26 21:08:30

[150000 rows x 5 columns]